spring:
  config:
    import:
      - "nacos:elderly-care-cloud-shared.yaml?refreshEnabled=true&group=DEFAULT_GROUP"
      - "nacos:elderly-ai.yaml?refreshEnabled=true&group=DEFAULT_GROUP"
  application:
    name: elderly-ai
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:8848
        namespace: 95fa0605-69e9-4b3b-8ecb-24feb2e63db3
      config:
        server-addr: ${NACOS_HOST:localhost}:8848
        file-extension: yaml
        namespace: 95fa0605-69e9-4b3b-8ecb-24feb2e63db3
server:
  port: 8087
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${AI_DASHSCOPE_API_KEY}
        model-name: qwen3.6-flash
        temperature: 0.4
        timeout: 60s
        log-requests: true
        log-responses: true
      streaming-chat-model:
        api-key: ${AI_DASHSCOPE_API_KEY}
        model-name: qwen3.6-flash

