spring:
  config:
    import:
      - "nacos:elderly-care-cloud-shared.yaml?refreshEnabled=true&group=DEFAULT_GROUP"
      - "nacos:elderly-auth.yaml?refreshEnabled=true&group=DEFAULT_GROUP"
  application:
    name: elderly-auth
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:8848
        namespace: 95fa0605-69e9-4b3b-8ecb-24feb2e63db3
      config:
        server-addr: ${NACOS_HOST:localhost}:8848
        file-extension: yaml
        namespace: 95fa0605-69e9-4b3b-8ecb-24feb2e63db3

server:
  port: 8081
